In [1]:
import numpy as np
import pandas as pd

bom_df = pd.read_csv('bom.movie_gross.csv.gz')

In [2]:
bom_df.head()

,title,studio,domestic_gross,foreign_gross,year
0,Toy Story 3,BV,415000000.0,652000000,2010
1,Alice in Wonderland (2010),BV,334200000.0,691300000,2010
2,Harry Potter and the Deathly Hallows Part 1,WB,296000000.0,664300000,2010
3,Inception,WB,292600000.0,535700000,2010
4,Shrek Forever After,P/DW,238700000.0,513900000,2010

In [3]:
bom_df.columns

Index(['title', 'studio', 'domestic_gross', 'foreign_gross', 'year'], dtype='object')

In [4]:
bom_df.studio.unique()

array(['BV', 'WB', 'P/DW', 'Sum.', 'Par.', 'Uni.', 'Fox', 'Wein.', 'Sony',
       'FoxS', 'SGem', 'WB (NL)', 'LGF', 'MBox', 'CL', 'W/Dim.', 'CBS',
       'Focus', 'MGM', 'Over.', 'Mira.', 'IFC', 'CJ', 'NM', 'SPC', 'ParV',
       'Gold.', 'JS', 'RAtt.', 'Magn.', 'Free', '3D', 'UTV', 'Rela.',
       'Zeit.', 'Anch.', 'PDA', 'Lorb.', 'App.', 'Drft.', 'Osci.', 'IW',
       'Rog.', nan, 'Eros', 'Relbig.', 'Viv.', 'Hann.', 'Strand', 'NGE',
       'Scre.', 'Kino', 'Abr.', 'CZ', 'ATO', 'First', 'GK', 'FInd.',
       'NFC', 'TFC', 'Pala.', 'Imag.', 'NAV', 'Arth.', 'CLS', 'Mont.',
       'Olive', 'CGld', 'FOAK', 'IVP', 'Yash', 'ICir', 'FM', 'Vita.',
       'WOW', 'Truly', 'Indic.', 'FD', 'Vari.', 'TriS', 'ORF', 'IM',
       'Elev.', 'Cohen', 'NeoC', 'Jan.', 'MNE', 'Trib.', 'Rocket',
       'OMNI/FSR', 'KKM', 'Argo.', 'SMod', 'Libre', 'FRun', 'WHE', 'P4',
       'KC', 'SD', 'AM', 'MPFT', 'Icar.', 'AGF', 'A23', 'Da.', 'NYer',
       'Rialto', 'DF', 'KL', 'ALP', 'LG/S', 'WGUSA', 'MPI', 'RTWC', 'FIP',
       'RF', 'ArcEnt', 'PalUni', 'EpicPics', 'EOne', 'LD', 'AF', 'TFA',
       'Myr.', 'BM&DH', 'SEG', 'PalT', 'Outs', 'OutF', 'BSM', 'WAMCR',
       'PM&E', 'A24', 'Cdgm.', 'Distrib.', 'Imax', 'PH', 'HTR', 'ELS',
       'PI', 'E1', 'TVC', 'FEF', 'EXCL', 'MSF', 'P/108', 'FCW', 'XL',
       'Shout!', 'SV', 'CE', 'VPD', 'KE', 'Saban', 'CF&SR', 'Triu', 'DR',
       'Crnth', 'Ampl.', 'CP', 'Proud', 'BGP', 'Abk.', 'DLA', 'B360',
       'BWP', 'SEA', 'RME', 'KS', 'VE', 'LGP', 'EC', 'FUN', 'STX', 'AR',
       'BG', 'PFR', 'BST', 'BH Tilt', 'BSC', 'U/P', 'UHE', 'CLF', 'FR',
       'AaF', 'Orch.', 'Alc', 'PBS', 'SHO', 'Grav.', 'Gathr', 'Asp.',
       'ADC', 'Rel.', 'SM', 'AZ', 'UEP', 'ITL', 'TA', 'MR', 'BBC',
       'CFilms', 'Part.', 'FOR', 'TAFC', 'JBG', 'PNT', 'CineGalaxy',
       'Fathom', 'Zee', 'Men.', 'YFG', 'Gaatri', 'Mon', 'Ghop',
       'Cleopatra', 'Dreamwest', 'SDS', 'Linn', 'Electric', 'Jampa', 'HC',
       'GrtIndia', 'Neon', 'ENTMP', 'Good Deed', 'ParC', 'Aviron',
       'Annapurna', 'Amazon', 'Affirm', 'MOM', 'Orion', 'CFI', 'UTMW',
       'Crimson', 'CAVU', 'EF', 'Arrow', 'Hiber', 'Studio 8',
       'Global Road', 'Trafalgar', 'Greenwich', 'Spanglish', 'Blue Fox',
       'RLJ', 'Swen', 'PackYourBag', 'Gaum.', 'Grindstone',
       'Conglomerate', 'MUBI', 'Darin Southa', 'Super', 'CARUSEL', 'PDF',
       'Synergetic'], dtype=object)

In [7]:
bom_df.year.unique()

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018])

In [8]:
imdb1_df = pd.read_csv('imdb.name.basics.csv.gz')

In [12]:
imdb_one_df = imdb1_df

In [14]:
imdb_one_df.columns

Index(['nconst', 'primary_name', 'birth_year', 'death_year',
       'primary_profession', 'known_for_titles'],
      dtype='object')

In [15]:
imdb_one_df.head()

,nconst,primary_name,birth_year,death_year,primary_profession,known_for_titles
0,nm0061671,Mary Ellen Bauder,NaN,NaN,"miscellaneous,production_manager,producer","tt0837562,tt2398241,tt0844471,tt0118553"
1,nm0061865,Joseph Bauer,NaN,NaN,"composer,music_department,sound_department","tt0896534,tt6791238,tt0287072,tt1682940"
2,nm0062070,Bruce Baum,NaN,NaN,"miscellaneous,actor,writer","tt1470654,tt0363631,tt0104030,tt0102898"
3,nm0062195,Axel Baumann,NaN,NaN,"camera_department,cinematographer,art_department","tt0114371,tt2004304,tt1618448,tt1224387"
4,nm0062798,Pete Baxter,NaN,NaN,"production_designer,art_department,set_decorator","tt0452644,tt0452692,tt3458030,tt2178256"

In [16]:
imdb_one_df.head(100)

,nconst,primary_name,birth_year,death_year,primary_profession,known_for_titles
0,nm0061671,Mary Ellen Bauder,NaN,NaN,"miscellaneous,production_manager,producer","tt0837562,tt2398241,tt0844471,tt0118553"
1,nm0061865,Joseph Bauer,NaN,NaN,"composer,music_department,sound_department","tt0896534,tt6791238,tt0287072,tt1682940"
2,nm0062070,Bruce Baum,NaN,NaN,"miscellaneous,actor,writer","tt1470654,tt0363631,tt0104030,tt0102898"
3,nm0062195,Axel Baumann,NaN,NaN,"camera_department,cinematographer,art_department","tt0114371,tt2004304,tt1618448,tt1224387"
4,nm0062798,Pete Baxter,NaN,NaN,"production_designer,art_department,set_decorator","tt0452644,tt0452692,tt3458030,tt2178256"
5,nm0062879,Ruel S. Bayani,NaN,NaN,"director,production_manager,miscellaneous","tt2590280,tt0352080,tt0216559,tt2057445"
6,nm0063198,Bayou,NaN,NaN,actor,"tt6579724,tt0093116"
7,nm0063432,Stevie Be-Zet,NaN,NaN,"composer,soundtrack","tt3106212,tt0478239,tt0264917,tt1626606"
8,nm0063618,Jeff Beal,1963.0,NaN,"composer,music_department,soundtrack","tt0183659,tt2545118,tt0384766,tt1856010"
9,nm0063750,Lindsay Beamish,NaN,NaN,"actress,miscellaneous","tt0404826,tt0111756,tt0367027,tt1492842"
10,nm0064023,Bryan Beasley,NaN,NaN,"director,producer,writer","tt3501180,tt1485100,tt1358897,tt1387162"
11,nm0064350,Martine Beauchemin,NaN,NaN,"producer,production_manager","tt5479010,tt0316463,tt1286159,tt0380732"
12,nm0065847,Michael Frost Beckner,1963.0,NaN,"writer,producer,miscellaneous","tt0108171,tt0095953,tt0266987,tt0285332"
13,nm0065919,Will Becton,NaN,NaN,"miscellaneous,editor,editorial_department","tt0478090,tt1334221,tt2249135,tt1522196"
14,nm0066093,Ahmad Bedair,1945.0,NaN,"actor,miscellaneous","tt2290391,tt0424830,tt0297398,tt2338117"
15,nm0066163,Arnaud Bedouët,NaN,NaN,"actor,writer,director","tt1355327,tt1977735,tt0173525,tt1710520"
16,nm0066268,Steve Mitchell Beebe,NaN,NaN,"editorial_department,director,editor","tt0827928,tt0119961,tt0408417,tt5521860"
17,nm0066897,Mohammad-Ali Behboudi,1956.0,NaN,actor,"tt6836462,tt4591834,tt0375911,tt2101473"
18,nm0067234,Hans Beimler,NaN,NaN,"producer,writer,miscellaneous","tt0486657,tt0092455,tt0091129,tt0106145"
19,nm0067845,Sondos Belhassen,NaN,NaN,actress,"tt0114103,tt0116209,tt1337140,tt0103806"
20,nm0067983,Krunoslav Belko,1971.0,NaN,actor,"tt1930421,tt0289360,tt0210629,tt3839316"
21,nm0068170,Dylan Bell,NaN,NaN,"director,actor,producer","tt4655766,tt3180116,tt8170168,tt4082762"
22,nm0068657,Philippe Bellaiche,NaN,NaN,"cinematographer,camera_department,producer","tt0309390,tt0285963,tt2091307,tt0498846"
23,nm0068874,Hava Kohav Beller,NaN,NaN,"director,writer,producer","tt0102778,tt7701650,tt0350668"
24,nm0069131,Gregg Bello,NaN,NaN,"actor,producer","tt1959490,tt5109784,tt1125849,tt0155267"
25,nm0069225,Gavin Bellour,NaN,NaN,"actor,producer,composer","tt0423370,tt2040257,tt0859592,tt7686128"
26,nm0069605,Bruno Beltramini,NaN,NaN,"cinematographer,visual_effects,camera_department","tt2154648,tt3746684,tt3746660,tt0427317"
27,nm0069757,Olga Belyavskaya,NaN,NaN,"actress,miscellaneous","tt0201345,tt7262530,tt0318034,tt1502417"
28,nm0069990,Jorge Ben Jor,1942.0,NaN,"soundtrack,composer,actor","tt0099892,tt3731562,tt1103275,tt0118655"
29,nm0070216,John Paul Fedele,NaN,NaN,"actor,cinematographer,special_effects","tt1424381,tt1075417,tt0453467,tt0268695"
...,...,...,...,...,...,...
70,nm0087103,Saga Blanchard,NaN,NaN,"miscellaneous,producer,actress","tt5038372,tt0409184,tt0869994,tt0830545"
71,nm0087190,Maurice Blanchot,1907.0,2003.0,writer,"tt7781736,tt0244050,tt9173540,tt1784698"
72,nm0087222,Alejandro Blanco Uribe,NaN,NaN,"composer,music_department,sound_department","tt0078892,tt0087659,tt0094652,tt0087853"
73,nm0087450,Mark Blaney,1969.0,NaN,"producer,miscellaneous","tt3733322,tt1429313,tt0310224,tt5797184"
74,nm0087595,Jamie Blanks,NaN,NaN,"composer,director,editor","tt0242998,tt1098356,tt0146336,tt1890375"
75,nm0087913,Jean Blaute,1952.0,NaN,"composer,actor,music_department","tt1889316,tt0149479,tt0093169,tt0222223"
76,nm0087933,Jacek Blawut,1950.0,NaN,"cinematographer,miscellaneous,director","tt1101672,tt1210349,tt0263792,tt0421774"
77,nm0088098,Jonah Blechman,1975.0,NaN,"actor,miscellaneous,producer","tt0443431,tt0181868,tt3333980,tt0108330"
78,nm0088531,Ryan Bliss,NaN,NaN,"director,writer,producer","tt2952898,tt3673638,tt4953592,tt4895946"
79,nm0088888,Eric Blom,NaN,NaN,"director,camera_department,writer","tt1388820,tt1185414,tt0140056,tt0272960"
80,nm0088949,Lars Blomgren,NaN,NaN,"producer,location_management,production_manager","tt6205766,tt1733785,tt1846197,tt0907683"
81,nm0089850,Lars Blumers,NaN,NaN,"director,writer,producer","tt0383585,tt0272963,tt1825703,tt1541655"
82,nm0089896,Colin Blunstone,1945.0,NaN,"soundtrack,actor","tt0104576,tt0119453,tt0058997,tt1395097"
83,nm0090420,Alexander Boboschewski,1962.0,NaN,"camera_department,cinematographer,actor","tt0813547,tt0108829,tt0858477,tt0252223"
84,nm0090847,Roberto Bodegas,1933.0,NaN,"director,assistant_director,writer","tt0065704,tt0071931,tt0074793,tt0072606"
85,nm0091773,Holt Boggs,1971.0,NaN,"actor,producer,writer","tt2699128,tt1124373,tt1064899,tt10189204"
86,nm0092307,Nicolas de Boiscuillé,NaN,NaN,"production_designer,set_decorator,actor","tt3399024,tt4333408,tt1661420,tt1790834"
87,nm0092526,David Christopher Loya,NaN,NaN,"producer,director,writer","tt7326174,tt5935104,tt5961192,tt2079475"
88,nm0093109,Don Bolles,1956.0,NaN,"actor,soundtrack,miscellaneous","tt2973412,tt0124442,tt0089907,tt4643048"
89,nm0093174,Ryan Bollman,1972.0,NaN,actor,"tt0096635,tt0106557,tt0107750,tt0090533"
90,nm0093284,Aleksandr Bokovikov,NaN,NaN,"producer,actor,assistant_director","tt2441862,tt1616552,tt0281357,tt5434152"
91,nm0093589,Matt Bomer,1977.0,NaN,"actor,producer,soundtrack","tt1637688,tt2268016,tt1915581,tt1684226"
92,nm0093674,Arcangelo Bonaccorso,NaN,NaN,"writer,director","tt3345788,tt0805498,tt0096755"
93,nm0094438,Tae-gyu Bong,NaN,NaN,actor,"tt0823462,tt0311373,tt0372782,tt0404777"
94,nm0094612,Daryl Bonilla,1975.0,NaN,"actor,director","tt1114239,tt10426940,tt0243609,tt2070513"
95,nm0094754,Emmanuelle Bonmariage,NaN,NaN,"actress,director","tt0272116,tt8322784,tt7994144"
96,nm0094756,Manu Bonmariage,1941.0,NaN,"cinematographer,director,camera_department","tt0128040,tt0308004,tt0252555,tt0257575"
97,nm0095089,Françoise Bonnot,1939.0,2018.0,"editor,actress,sound_department","tt0445922,tt0084335,tt0074811,tt0065234"
98,nm0096073,Óscar Borda,NaN,NaN,"actor,music_department,soundtrack","tt0486070,tt0371476,tt1157631,tt0224945"
99,nm0096983,Wes Borland,1975.0,NaN,"soundtrack,composer,music_department","tt0489270,tt0432348,tt0433035,tt0320691"

In [19]:
type(imdb_one_df['birth_year'][0])

numpy.float64

In [20]:
type(imdb_one_df['death_year'][0])

numpy.float64

In [23]:
imdb_one_df['primary_profession'][0][6:12]

'laneou'

In [25]:
type(imdb_one_df['known_for_titles'][0])

str

In [26]:
imdb_two_df = pd.read_csv('imdb.title.akas.csv.gz')
imdb_two_df.head()

,title_id,ordering,title,region,language,types,attributes,is_original_title
0,tt0369610,10,Джурасик свят,BG,bg,NaN,NaN,0.0
1,tt0369610,11,Jurashikku warudo,JP,NaN,imdbDisplay,NaN,0.0
2,tt0369610,12,Jurassic World: O Mundo dos Dinossauros,BR,NaN,imdbDisplay,NaN,0.0
3,tt0369610,13,O Mundo dos Dinossauros,BR,NaN,NaN,short title,0.0
4,tt0369610,14,Jurassic World,FR,NaN,imdbDisplay,NaN,0.0

# Information on the individual data sets:

## Box Office Mojo (bom.movie_gross.csv.gz)

Columns: *title, studio, domestic_gross, foreign_gross, year*

* **title**: Type = str.  Appears to be only in English.
* **studio**: Type = str.  They are all abbreviations (BV = Buena Vista, Sum. = Summit, etc.)
* **domestic_gross**: Type = float64.  In US Dollars.
* **foreign_gross**: Type = float64.  In US Dollars.
* **year**: Type = int64.  Year of release.

## IMDB

### IMDB name basics (imdb.name.basics.csv.gz)

Columns: *nconst, primary_name, birth_year, death_year, primary_profession, known_for_titles*

* **nconst**: Type = str.  IMDB name identifier for a person.
* **primary_name**: Type = str.  Full name of person, can be multiple words.
* **birth_year**: Type = float64.
* **death_year**: Type = float64.
* **known_for_titles**: Type = str.  IMDB identifier(s) for film titles.  Can be multiple identifiers separated by commas.

In [42]:
imdb_one_df.known_for_titles[0:100]

0      tt0837562,tt2398241,tt0844471,tt0118553
1      tt0896534,tt6791238,tt0287072,tt1682940
2      tt1470654,tt0363631,tt0104030,tt0102898
3      tt0114371,tt2004304,tt1618448,tt1224387
4      tt0452644,tt0452692,tt3458030,tt2178256
5      tt2590280,tt0352080,tt0216559,tt2057445
6                          tt6579724,tt0093116
7      tt3106212,tt0478239,tt0264917,tt1626606
8      tt0183659,tt2545118,tt0384766,tt1856010
9      tt0404826,tt0111756,tt0367027,tt1492842
10     tt3501180,tt1485100,tt1358897,tt1387162
11     tt5479010,tt0316463,tt1286159,tt0380732
12     tt0108171,tt0095953,tt0266987,tt0285332
13     tt0478090,tt1334221,tt2249135,tt1522196
14     tt2290391,tt0424830,tt0297398,tt2338117
15     tt1355327,tt1977735,tt0173525,tt1710520
16     tt0827928,tt0119961,tt0408417,tt5521860
17     tt6836462,tt4591834,tt0375911,tt2101473
18     tt0486657,tt0092455,tt0091129,tt0106145
19     tt0114103,tt0116209,tt1337140,tt0103806
20     tt1930421,tt0289360,tt0210629,tt3839316
21     tt4655766,tt3180116,tt8170168,tt4082762
22     tt0309390,tt0285963,tt2091307,tt0498846
23               tt0102778,tt7701650,tt0350668
24     tt1959490,tt5109784,tt1125849,tt0155267
25     tt0423370,tt2040257,tt0859592,tt7686128
26     tt2154648,tt3746684,tt3746660,tt0427317
27     tt0201345,tt7262530,tt0318034,tt1502417
28     tt0099892,tt3731562,tt1103275,tt0118655
29     tt1424381,tt1075417,tt0453467,tt0268695
                        ...
70     tt5038372,tt0409184,tt0869994,tt0830545
71     tt7781736,tt0244050,tt9173540,tt1784698
72     tt0078892,tt0087659,tt0094652,tt0087853
73     tt3733322,tt1429313,tt0310224,tt5797184
74     tt0242998,tt1098356,tt0146336,tt1890375
75     tt1889316,tt0149479,tt0093169,tt0222223
76     tt1101672,tt1210349,tt0263792,tt0421774
77     tt0443431,tt0181868,tt3333980,tt0108330
78     tt2952898,tt3673638,tt4953592,tt4895946
79     tt1388820,tt1185414,tt0140056,tt0272960
80     tt6205766,tt1733785,tt1846197,tt0907683
81     tt0383585,tt0272963,tt1825703,tt1541655
82     tt0104576,tt0119453,tt0058997,tt1395097
83     tt0813547,tt0108829,tt0858477,tt0252223
84     tt0065704,tt0071931,tt0074793,tt0072606
85    tt2699128,tt1124373,tt1064899,tt10189204
86     tt3399024,tt4333408,tt1661420,tt1790834
87     tt7326174,tt5935104,tt5961192,tt2079475
88     tt2973412,tt0124442,tt0089907,tt4643048
89     tt0096635,tt0106557,tt0107750,tt0090533
90     tt2441862,tt1616552,tt0281357,tt5434152
91     tt1637688,tt2268016,tt1915581,tt1684226
92               tt3345788,tt0805498,tt0096755
93     tt0823462,tt0311373,tt0372782,tt0404777
94    tt1114239,tt10426940,tt0243609,tt2070513
95               tt0272116,tt8322784,tt7994144
96     tt0128040,tt0308004,tt0252555,tt0257575
97     tt0445922,tt0084335,tt0074811,tt0065234
98     tt0486070,tt0371476,tt1157631,tt0224945
99     tt0489270,tt0432348,tt0433035,tt0320691
Name: known_for_titles, Length: 100, dtype: object